In [3]:
import numpy as np
import pandas as pd

arr = np.array(pd.read_csv('GenerateData/0.csv', dtype=int))

for i in range(1,1000):
    df = pd.read_csv('GenerateData/'+str(i)+'.csv')
    arr = np.concatenate((arr, np.array(df)), axis=0)

arrF = arr.reshape(-1,300,9)
print(arrF.shape)
print(arrF)

(1000, 300, 9)
[[[     0 615483 310798 ... 677303 721480 980332]
  [     1 683101 512018 ... 176519 134423 441712]
  [     2 160319 605512 ...  64470 594263 151447]
  ...
  [   297 146945 128808 ... 844331 387044 153103]
  [   298 275899 844122 ... 549366 945833 518925]
  [   299 325089 223079 ... 201657 143916 846204]]

 [[     0 861110 502915 ... 280700 834145  12143]
  [     1 679622 614053 ... 966485 996481 542099]
  [     2  55765 673550 ... 104531 934580 289715]
  ...
  [   297  74510 950541 ... 320128 644393 537592]
  [   298 544413 439727 ... 315287  76952 585390]
  [   299 893028 105316 ... 855207 394845 942789]]

 [[     0 109829 221181 ... 522503 258738 300205]
  [     1 226974 491978 ... 657035 902516  73549]
  [     2 898370 881477 ... 212080 735481 142176]
  ...
  [   297 709991  17774 ... 403208 170048 588444]
  [   298 199880 472165 ... 304202 362181 622990]
  [   299 413906 755817 ... 460981 744110 160285]]

 ...

 [[     0 112759 624047 ... 193970 607149 710336]
  [  